# Generated by Django 4.0.2 on 2022-02-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='wrtier',
            new_name='writer',
        ),
    ]
